---
title: "May Institute 2019: Beginner's statistics in R"
author: "Laurent Gatto and Meena Choi"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
biblio-style: apalike
link-citations: yes
---

# Before we start {-}

- Download the data files here: https://lgatto.github.io/MayInstituteRstatsIntro/RIntro.zip
- A pdf version of the course is available here: https://lgatto.github.io/MayInstituteRstatsIntro/RIntro.pdf

## Suggested reading {-}

* [Points of Significance : Statistics for Biologists](https://www.nature.com/collections/qghhqm/pointsofsignificance)

## Schedule {-}


| Day | Time            | Content                                                                                            |
|-----|-----------------|----------------------------------------------------------------------------------------------------|
| 1   | 1:30 - 3:00pm   | Lecture: Introduction to statistics (OV)                                                           |
|     | 3:00 - 3:30pm   | Refreshments                                                                                       |
|     | 3:30 - 5:00pm   | R basics and RStudio (LG)                                                                          |
|     | 5:00 - 6:00pm   | R markdown (LG)                                                                                    |
| 2   | 8:00 - 9:00am   | Q&A                                                                                                |
|     | 9:00 - 10:30am  | Data Exploration (LG)                                                                              |
|     | 10:30 - 11:00am | Refreshments                                                                                       |
|     | 11:00 - 12:30pm | Data Exploration 2 (LG)                                                                            |
|     | 12:30 - 13:30pm | Lunch break                                                                                        |
|     | 13:30 - 3:00pm  | Lecture: Statistical inference (OV)                                                                |
|     | 3:00 - 3:30pm   | Refreshments                                                                                       |
|     | 3:30 - 5:00pm   | Visualisation (LG)                                                                                 |
|     | 5:00 - 6:00pm   | Extra practice                                                                                     |
| 3   | 8:00 - 9:00am   | Q&A                                                                                                |
|     | 9:00 - 10:30am  | Randomisation, summaries, error bars and confidence intervals (MC)                                 |
|     | 10:30 - 11:00am | Refreshments                                                                                       |
|     | 11:00 - 12:30pm | Lecture: sample size, linear regression, categorical data (OV)                                     |
|     | 12:30 - 13:30pm | Lunch break                                                                                        |
|     | 13:30 - 3:00pm  | Hypothesis testing and categorical data (MC)                                                       |
|     | 3:00 - 3:30pm   | Refreshments                                                                                       |
|     | 3:30 - 4:15pm   | Samples size calculation, linear models and correlation (MC)                                       |
|     | 4:15 - 5:00pm   | Introduction to [`MSnbase`](https://bioconductor.org/packages/release/bioc/html/MSnbase.html) (LG)        |
|     | 5:00 - 6:00pm   | Wrap-up                                                                                            |


Olga Vitek (OV), Meena Choi (MC), Laurent Gatto (LG)


## License {-}


This material, unless otherwise stated, is made available under the
[Creative Commons Attribution
license](https://creativecommons.org/licenses/by/4.0/).

You are free to:

* **Share** - copy and redistribute the material in any medium or format
* **Adapt** - remix, transform, and build upon the material for any
  purpose, even commercially.

The licensor cannot revoke these freedoms as long as you follow the license terms.

Under the following terms:

* **Attribution** - You must give appropriate credit, provide a link
  to the license, and indicate if changes were made. You may do so in
  any reasonable manner, but not in any way that suggests the licensor
  endorses you or your use.

No additional restrictions - You may not apply legal terms or
technological measures that legally restrict others from doing
anything the license permits.

## Credit {-}

Some of the material from day 1 and 2 has been adapted from the Data
Carpentry R lessons (see references in the respective sections), which
are also licensed under CC-BY.
